<?php

namespace Cib\Bundle\LicenseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TokenClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenClientRepository extends EntityRepository
{
}
